# Generated by Django 2.0.2 on 2018-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='img',
            field=models.ImageField(default='photo/test.png', upload_to='photo'),
        ),
    ]
